### ISSUE TITLE
More descriptive error message when sources-path directory doesnt exist

### ISSUE THREAD

**Issue by staabm** [Roave/BackwardCompatibilityCheck#101] opened 2018-08-21 20:37 UTC
Atm the command exits with an error mentioning a path which doesnt exist, but does not provide a hint to the user that the actual given parameter is at fault
(Or in case the project doesnt has the sources in /src its even harder to get whats wrong)

**Comment by Ocramius** [comment] 2018-08-21 20:41
@staabm that would be the first argument of the CLI tool: possible duplicate of https://github.com/Roave/BackwardCompatibilityCheck/pull/97 ?

**Comment by staabm** [comment] 2018-08-21 20:47
I guess you are right.

Could you give me a hint, why the command doesnt work?
https://travis-ci.org/redaxo/redaxo/jobs/418885955

**Comment by Ocramius** [comment] 2018-08-21 20:51
That's because in symfony CLI commands, the first argument is the command name, even if a default command is specified. You will have to type following when providing an argument:

```sh
vendor/bin/roave-backward-compatibility-check roave-backwards-compatibility-check:assert-backwards-compatible --from=master --to=HEAD -- redaxo/src
```

Or, shorter:


```sh
vendor/bin/roave-backward-compatibility-check r:a --from=master --to=HEAD -- redaxo/src
```

**Comment by staabm** [comment] 2018-08-21 20:57
Thanks, that was my problem.

I guess DX wise this ugly arg construction could be „worked arround“ by defining the sources-path as a option instead of a argument

**Comment by staabm** [comment] 2018-08-21 20:58
(Unrelated 2nd problem: in our project, the composer.json is not placed within the repo-root. I guess thats a edge case the lib does not yet support?)

**Comment by Ocramius** [comment] 2018-08-21 21:01
> not yet support

And won't support. Non-root `composer.json` hugely deviates from standards, so it is advisable to build your own CLI entry-point script based on classes provided by this package.

If this is a deal-breaker, I suggest helping out on #97 before I do, because I'll surely close off the "`composer.json` in non-standard locations" scenario :-P

Meanwhile, closing here as a duplicate of #97

**Closed by Ocramius** 2018-08-21 21:01 UTC
Labels: enhancement, question

**Comment by staabm** [comment] 2018-08-21 21:05
I see. Thx for your input.
